import { ItemProps } from "@/components";
import * as Crypto from "expo-crypto";

export const popularItemsData: ItemProps[] = [
  {
    uuid: Crypto.randomUUID(),
    slug: Crypto.randomUUID(),
    id: "p-001",
    name: "beautiful product categories sub look ",
    price: 1599,
    rating: 4.5,
    discount: 4,
    location: "Bagmati Province",
    freeDelivery: true,
    specialSale: {
      discountType: "percent",
      discount: 72,
      endDate: "2025-02-31 02:12:00",
      name: "Special Sale Price",
    },
  },
  {
    uuid: Crypto.randomUUID(),
    slug: Crypto.randomUUID(),
    id: "p-002",
    name: "very beautiful product categories sub look ",
    price: 1599,
    rating: 4.5,
    discount: 1,
    location: "Bagmati Province",
  },
  {
    uuid: Crypto.randomUUID(),
    slug: Crypto.randomUUID(),
    id: "p-003",
    name: "beautiful product categories sub look ",
    price: 1599,
    rating: 4.5,
    discount: 4,
    location: "Kaski Province",
    specialSale: {
      discountType: "percent",
      discount: 72,
      endDate: "2025-02-31 02:12:00",
      name: "Special Sale Price",
    },
  },
  {
    uuid: Crypto.randomUUID(),
    slug: Crypto.randomUUID(),
    id: "p-004",
    name: "beautiful product categories sub look ",
    price: 1599,
    rating: 4.5,
    discount: 4,
    location: "Bagmati Province",
  },
  {
    uuid: Crypto.randomUUID(),
    slug: Crypto.randomUUID(),
    id: "p-005",
    name: "beautiful product categories sub look ",
    price: 1599,
    rating: 4.5,
    discount: 4,
    location: "Kaski Province",
  },
  {
    uuid: Crypto.randomUUID(),
    slug: Crypto.randomUUID(),
    id: "p-006",
    name: "beautiful product categories sub look ",
    price: 1599,
    rating: 4.5,
    location: "Bagmati Province",
    discount: 4,
  },
  {
    uuid: Crypto.randomUUID(),
    slug: Crypto.randomUUID(),
    id: "p-007",
    name: "beautiful product categories sub look ",
    price: 1599,
    rating: 4.5,
    location: "Bagmati Province",
    discount: 4,
  },
  {
    uuid: Crypto.randomUUID(),
    slug: Crypto.randomUUID(),
    id: "p-008",
    name: "beautiful product categories sub look ",
    price: 1599,
    rating: 4.5,
    location: "Bagmati Province",
    discount: 4,
  },
  {
    uuid: Crypto.randomUUID(),
    slug: Crypto.randomUUID(),
    id: "p-009",
    name: "beautiful product categories sub look ",
    price: 1599,
    rating: 4.5,
    location: "Bagmati Province",
    discount: 4,
  },
  {
    uuid: Crypto.randomUUID(),
    slug: Crypto.randomUUID(),
    id: "p-001599",
    name: "beautiful product categories sub look ",
    price: 1599,
    rating: 4.5,
    location: "Bagmati Province",
    discount: 4,
  },
];
